export default [
    {
        upper: 'A',
    }, {
        upper: 'B',
    }, {
        upper: 'C',
    }, {
        upper: 'D',
    }, {
        upper: 'E',
    }, {
        upper: 'F',
    }, {
        upper: 'G',
    }, {
        upper: 'H',
    }, {
        upper: 'I',
    }, {
        upper: 'J',
    }, {
        upper: 'K',
    }, {
        upper: 'L',
    }, {
        upper: 'M',
    }, {
        upper: 'N',
    }, {
        upper: 'O',
    }, {
        upper: 'P',
    }, {
        upper: 'Q',
    }, {
        upper: 'R',
    }, {
        upper: 'S',
    }, {
        upper: 'T',
    }, {
        upper: 'U',
    }, {
        upper: 'V',
    }, {
        upper: 'W',
    }, {
        upper: 'X',
    }, {
        upper: 'Y',
    }, {
        upper: 'Z',
    },
]